### ISSUE TITLE
Analyze next app in sub-directory

### ISSUE THREAD

**Issue by jstcki** [niquis/action#17]
Would be awesome if Niquis can analyze an app in ./app, ./website etc. 👌

**Comment by wereHamster** [comment]
I wanted to make the action configurable via a config file anyways, such that you can choose which plugins you want to use, and configure them separately. Something like:

```yaml
apiVersion: v1
use:
 - plugin: nextjs
   directory: app
 - plugin: npm
   directory: .
```

**Comment by jstcki** [comment]
Couldn't this be parameterized via the workflow file? E.g. https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepswith

**Comment by jstcki** [comment]
And apiVersion could just match version number of the action itself? I.e. `niquis/action@v1`

**Comment by wereHamster** [comment]
It looks like you can only use simple string key/value pairs with the github action syntax. It could get quite complicated if we wanted to support configuring multiple plugins via action params. But I'm open to suggestions.

Regarding the version in the config file, we can make it optional, but I think it's useful information to have for the future. I would love to offer the core logic as a CLI tool, so you can run/test it locally, and then the version becomes a useful information for the tool to report incompatibilities, offer upgrade instructions etc…

**Comment by wereHamster** [comment]
https://github.com/niquis/action#setup

I won't make any guarantees about the config file format, but as of now, it should support subdirectories:

```yaml
version: v0
collect:
  - type: next.js
    directory: app
```
